@csrf
<div class="grid gap-6 lg:grid-cols-2">
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Section Type *</label><select name="section_type" required class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-200">@foreach($sectionTypes as $key=>$label)<option value="{{ $key }}" @selected(old('section_type',$section->section_type ?? '')===$key)>{{ $label }}</option>@endforeach</select></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Status *</label><select name="status" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm"><option value="active" @selected(old('status',$section->status ?? 'active')==='active')>Active</option><option value="inactive" @selected(old('status',$section->status ?? '')==='inactive')>Inactive</option></select></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Title (English)</label><input name="title_en" value="{{ old('title_en',$section->title_en ?? '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-200"></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Title (Bangla)</label><input name="title_bn" value="{{ old('title_bn',$section->title_bn ?? '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-200"></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Subtitle (English)</label><input name="subtitle_en" value="{{ old('subtitle_en',$section->subtitle_en ?? '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm"></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Subtitle (Bangla)</label><input name="subtitle_bn" value="{{ old('subtitle_bn',$section->subtitle_bn ?? '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm"></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Content (English)</label><textarea name="content_en" rows="6" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm">{{ old('content_en',$section->content_en ?? '') }}</textarea></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Content (Bangla)</label><textarea name="content_bn" rows="6" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm">{{ old('content_bn',$section->content_bn ?? '') }}</textarea></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Media ID (optional)</label><select name="media_id" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm"><option value="">No media</option>@foreach($media as $item)<option value="{{ $item->id }}" @selected(old('media_id',$section->media_id ?? '')===$item->id)>{{ $item->original_name ?: $item->file_name }} — {{ $item->id }}</option>@endforeach</select></div>
<div><label class="mb-2 block text-sm font-semibold text-gray-700">Sort Order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$section->sort_order ?? 0) }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm shadow-sm"></div>
</div>
<div class="mt-6"><label class="mb-2 block text-sm font-semibold text-gray-700">Section Data (JSON)</label><textarea name="data_json" rows="12" class="w-full rounded-lg border border-gray-300 bg-gray-50 px-4 py-3 font-mono text-sm shadow-sm focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-200" placeholder='{"items":[],"button":{"label_en":"Learn More","label_bn":"আরও জানুন"}}'>{{ old('data_json',isset($section) && $section->data ? json_encode($section->data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea><p class="mt-1 text-xs text-gray-500">Use this for section-specific fields. The public API returns it as JSON.</p></div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ route('admin.pages.edit',$page) }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 shadow-sm hover:bg-gray-50">Cancel</a><button class="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-gray-800">Save Section</button></div>
