@extends('admin.layouts.app')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-2xl font-semibold text-slate-900">Gallery Categories</h1><p class="mt-1 text-sm text-slate-500">Organize galleries into categories.</p></div><a href="{{ route('admin.gallery-categories.create') }}" class="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-medium text-white">Create Category</a></div>
    @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ session('error') }}</div>@endif
    <div class="rounded-2xl border border-gray-200 bg-white p-5"><form method="GET" class="grid gap-3 md:grid-cols-3"><input name="search" value="{{ request('search') }}" placeholder="Search categories..." class="rounded-xl border border-gray-300 px-3 py-2.5 text-sm"><select name="status" class="rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><button class="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-medium text-white">Filter</button></form></div>
    <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-gray-200 bg-slate-50"><tr><th class="px-5 py-3 font-medium">Category</th><th class="px-5 py-3 font-medium">Status</th><th class="px-5 py-3 font-medium">Galleries</th><th class="px-5 py-3 text-right font-medium">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($categories as $category)<tr class="hover:bg-slate-50"><td class="px-5 py-4"><div class="font-medium">{{ $category->name_en }}</div><div class="text-xs text-slate-500">{{ $category->name_bn }}</div></td><td class="px-5 py-4">{{ ucfirst($category->status) }}</td><td class="px-5 py-4">{{ $category->galleries_count }}</td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2"><a href="{{ route('admin.gallery-categories.edit',$category) }}" class="rounded-lg border border-gray-300 px-3 py-1.5 text-xs">Edit</a><form method="POST" action="{{ route('admin.gallery-categories.destroy',$category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-600">Delete</button></form></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-sm text-slate-500">No categories found.</td></tr>@endforelse</tbody></table></div><div class="border-t border-gray-200 px-5 py-4">{{ $categories->links() }}</div></div>
</div>
@endsection
