<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name',100)->unique(); $t->string('slug',100)->unique(); $t->text('description')->nullable(); $t->timestamps(); });
        Schema::create('user_roles', function (Blueprint $t) { $t->foreignId('user_id')->constrained('users')->cascadeOnDelete(); $t->uuid('role_id'); $t->primary(['user_id','role_id']); $t->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); });
        Schema::create('media', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('file_name'); $t->string('original_name')->nullable(); $t->text('file_path'); $t->string('disk',50)->default('public'); $t->string('mime_type',100)->nullable(); $t->unsignedBigInteger('file_size')->nullable(); $t->string('alt_text')->nullable(); $t->string('title')->nullable(); $t->text('caption')->nullable(); $t->json('metadata')->nullable(); $t->timestamps(); });
        Schema::create('pages', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('parent_id')->nullable(); $t->string('title'); $t->string('slug')->unique(); $t->string('page_type',50)->default('standard'); $t->text('short_description')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->integer('sort_order')->default(0); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('parent_id')->references('id')->on('pages')->nullOnDelete(); });
        Schema::create('page_sections', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('page_id'); $t->string('section_type',100); $t->string('title')->nullable(); $t->string('subtitle')->nullable(); $t->longText('content')->nullable(); $t->uuid('media_id')->nullable(); $t->json('data')->nullable(); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); $t->foreign('page_id')->references('id')->on('pages')->cascadeOnDelete(); $t->foreign('media_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('navigations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name',100); $t->string('slug',100)->unique(); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); });
        Schema::create('navigation_items', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('navigation_id'); $t->uuid('parent_id')->nullable(); $t->string('title'); $t->enum('link_type',['page','url'])->default('page'); $t->uuid('page_id')->nullable(); $t->text('url')->nullable(); $t->enum('target',['_self','_blank'])->default('_self'); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); $t->foreign('navigation_id')->references('id')->on('navigations')->cascadeOnDelete(); $t->foreign('parent_id')->references('id')->on('navigation_items')->cascadeOnDelete(); $t->foreign('page_id')->references('id')->on('pages')->nullOnDelete(); });
        Schema::create('programs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->unique(); $t->text('short_description')->nullable(); $t->longText('description')->nullable(); $t->uuid('featured_image_id')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->integer('sort_order')->default(0); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('projects', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('program_id')->nullable(); $t->string('title'); $t->string('slug')->unique(); $t->text('short_description')->nullable(); $t->longText('description')->nullable(); $t->uuid('featured_image_id')->nullable(); $t->string('location')->nullable(); $t->date('start_date')->nullable(); $t->date('end_date')->nullable(); $t->enum('status',['draft','planned','active','completed','archived'])->default('draft'); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('program_id')->references('id')->on('programs')->nullOnDelete(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('project_activities', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('project_id'); $t->string('title'); $t->text('description')->nullable(); $t->date('activity_date')->nullable(); $t->string('location')->nullable(); $t->enum('status',['planned','completed','cancelled'])->default('planned'); $t->integer('sort_order')->default(0); $t->timestamps(); $t->foreign('project_id')->references('id')->on('projects')->cascadeOnDelete(); });
        Schema::create('project_metrics', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('project_id'); $t->string('metric_name',150); $t->string('metric_value',100); $t->string('metric_unit',100)->nullable(); $t->text('description')->nullable(); $t->integer('sort_order')->default(0); $t->timestamps(); $t->foreign('project_id')->references('id')->on('projects')->cascadeOnDelete(); });
        Schema::create('project_budgets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('project_id'); $t->string('category',150); $t->text('description')->nullable(); $t->decimal('allocated_amount',15,2)->default(0); $t->decimal('spent_amount',15,2)->default(0); $t->char('currency',3)->default('BDT'); $t->integer('sort_order')->default(0); $t->timestamps(); $t->foreign('project_id')->references('id')->on('projects')->cascadeOnDelete(); });
        Schema::create('people', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('designation')->nullable(); $t->longText('biography')->nullable(); $t->uuid('photo_id')->nullable(); $t->string('email')->nullable(); $t->string('phone',50)->nullable(); $t->json('social_links')->nullable(); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); $t->foreign('photo_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('partners', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('slug')->nullable()->unique(); $t->text('description')->nullable(); $t->uuid('logo_id')->nullable(); $t->string('website_url',500)->nullable(); $t->string('partner_type',100)->nullable(); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); $t->foreign('logo_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('resources', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->nullable()->unique(); $t->text('description')->nullable(); $t->string('resource_type',100)->nullable(); $t->uuid('file_id')->nullable(); $t->date('publication_date')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamps(); $t->foreign('file_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('articles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->unique(); $t->text('excerpt')->nullable(); $t->longText('body'); $t->uuid('featured_image_id')->nullable(); $t->uuid('author_id')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->timestamp('published_at')->nullable(); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamps(); $t->foreign('author_id')->references('id')->on('people')->nullOnDelete(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('news', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->unique(); $t->text('excerpt')->nullable(); $t->longText('body'); $t->uuid('featured_image_id')->nullable(); $t->uuid('author_id')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->timestamp('published_at')->nullable(); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamps(); $t->foreign('author_id')->references('id')->on('people')->nullOnDelete(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('faq_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name',150); $t->string('slug',150)->unique(); $t->text('description')->nullable(); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); });
        Schema::create('faqs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('category_id')->nullable(); $t->text('question'); $t->longText('answer'); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); $t->foreign('category_id')->references('id')->on('faq_categories')->nullOnDelete(); });
        Schema::create('gallery_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name',150); $t->string('slug',150)->unique(); $t->text('description')->nullable(); $t->integer('sort_order')->default(0); $t->enum('status',['active','inactive'])->default('active'); $t->timestamps(); });
        Schema::create('galleries', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('category_id')->nullable(); $t->string('title'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->uuid('cover_image_id')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('category_id')->references('id')->on('gallery_categories')->nullOnDelete(); $t->foreign('cover_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('gallery_photos', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('gallery_id'); $t->uuid('media_id'); $t->text('caption')->nullable(); $t->string('alt_text')->nullable(); $t->integer('sort_order')->default(0); $t->timestamps(); $t->foreign('gallery_id')->references('id')->on('galleries')->cascadeOnDelete(); $t->foreign('media_id')->references('id')->on('media')->cascadeOnDelete(); });
        Schema::create('video_galleries', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->timestamp('published_at')->nullable(); $t->timestamps(); });
        Schema::create('videos', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('gallery_id')->nullable(); $t->string('title'); $t->string('slug')->nullable()->unique(); $t->text('description')->nullable(); $t->string('video_provider',50)->nullable(); $t->string('video_url',500); $t->string('video_id')->nullable(); $t->uuid('thumbnail_id')->nullable(); $t->timestamp('published_at')->nullable(); $t->enum('status',['draft','published','archived'])->default('draft'); $t->integer('sort_order')->default(0); $t->timestamps(); $t->foreign('gallery_id')->references('id')->on('video_galleries')->nullOnDelete(); $t->foreign('thumbnail_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('events', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('title'); $t->string('slug')->unique(); $t->longText('description')->nullable(); $t->uuid('featured_image_id')->nullable(); $t->string('location',500)->nullable(); $t->dateTime('start_at')->nullable(); $t->dateTime('end_at')->nullable(); $t->string('registration_url',500)->nullable(); $t->enum('status',['draft','upcoming','ongoing','completed','cancelled','archived'])->default('draft'); $t->timestamp('published_at')->nullable(); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamps(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('volunteer_applications', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('email'); $t->string('phone',50)->nullable(); $t->text('address')->nullable(); $t->string('occupation')->nullable(); $t->text('skills')->nullable(); $t->text('interests')->nullable(); $t->text('message')->nullable(); $t->enum('status',['pending','reviewing','approved','rejected','archived'])->default('pending'); $t->text('admin_notes')->nullable(); $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('reviewed_at')->nullable(); $t->timestamps(); });
        Schema::create('campaigns', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('project_id')->nullable(); $t->uuid('program_id')->nullable(); $t->string('title'); $t->string('slug')->unique(); $t->text('short_description')->nullable(); $t->longText('description')->nullable(); $t->uuid('featured_image_id')->nullable(); $t->decimal('target_amount',15,2)->nullable(); $t->char('currency',3)->default('BDT'); $t->date('start_date')->nullable(); $t->date('end_date')->nullable(); $t->enum('status',['draft','active','completed','cancelled','archived'])->default('draft'); $t->boolean('is_featured')->default(false); $t->string('seo_title')->nullable(); $t->text('seo_description')->nullable(); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('project_id')->references('id')->on('projects')->nullOnDelete(); $t->foreign('program_id')->references('id')->on('programs')->nullOnDelete(); $t->foreign('featured_image_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('donations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('campaign_id')->nullable(); $t->string('donor_name')->nullable(); $t->string('donor_email')->nullable(); $t->string('donor_phone',50)->nullable(); $t->decimal('amount',15,2); $t->char('currency',3)->default('BDT'); $t->string('payment_method',50)->nullable(); $t->boolean('is_anonymous')->default(false); $t->text('message')->nullable(); $t->enum('status',['pending','processing','completed','failed','cancelled','refunded'])->default('pending'); $t->timestamps(); $t->foreign('campaign_id')->references('id')->on('campaigns')->nullOnDelete(); });
        Schema::create('payment_transactions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('donation_id'); $t->string('gateway',100); $t->string('transaction_id')->nullable(); $t->string('gateway_transaction_id')->nullable(); $t->string('payment_method',100)->nullable(); $t->decimal('amount',15,2); $t->char('currency',3)->default('BDT'); $t->enum('status',['initiated','pending','success','failed','cancelled','refunded'])->default('initiated'); $t->json('gateway_response')->nullable(); $t->timestamp('paid_at')->nullable(); $t->timestamps(); $t->unique(['gateway','transaction_id']); $t->foreign('donation_id')->references('id')->on('donations')->cascadeOnDelete(); });
        Schema::create('sponsored_children', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('child_code',100)->unique(); $t->string('display_name'); $t->unsignedInteger('age')->nullable(); $t->string('gender',50)->nullable(); $t->text('short_bio')->nullable(); $t->uuid('photo_id')->nullable(); $t->string('location')->nullable(); $t->enum('status',['available','sponsored','inactive'])->default('available'); $t->timestamps(); $t->foreign('photo_id')->references('id')->on('media')->nullOnDelete(); });
        Schema::create('sponsorships', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('child_id'); $t->string('sponsor_name'); $t->string('sponsor_email')->nullable(); $t->string('sponsor_phone',50)->nullable(); $t->decimal('amount',15,2)->nullable(); $t->char('currency',3)->default('BDT'); $t->date('start_date')->nullable(); $t->date('end_date')->nullable(); $t->enum('status',['pending','active','completed','cancelled'])->default('pending'); $t->text('admin_notes')->nullable(); $t->timestamps(); $t->foreign('child_id')->references('id')->on('sponsored_children')->restrictOnDelete(); });
        Schema::create('contact_submissions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('email'); $t->string('phone',50)->nullable(); $t->string('subject')->nullable(); $t->text('message'); $t->enum('status',['unread','read','replied','archived'])->default('unread'); $t->text('admin_notes')->nullable(); $t->foreignId('handled_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('handled_at')->nullable(); $t->timestamps(); });
        Schema::create('site_settings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('setting_key',150)->unique(); $t->text('setting_value')->nullable(); $t->enum('setting_type',['text','textarea','number','boolean','json','image','url'])->default('text'); $t->boolean('is_public')->default(true); $t->timestamps(); });
        Schema::create('idempotency_keys', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('idempotency_key')->unique(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('endpoint'); $t->string('request_hash')->nullable(); $t->integer('response_status')->nullable(); $t->json('response_body')->nullable(); $t->timestamp('expires_at')->nullable(); $t->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',100); $t->string('entity_type',100)->nullable(); $t->uuid('entity_id')->nullable(); $t->json('old_values')->nullable(); $t->json('new_values')->nullable(); $t->string('ip_address',45)->nullable(); $t->text('user_agent')->nullable(); $t->timestamp('created_at')->useCurrent(); });
    }

    public function down(): void
    {
        foreach (['audit_logs','idempotency_keys','site_settings','contact_submissions','sponsorships','sponsored_children','payment_transactions','donations','campaigns','volunteer_applications','events','videos','video_galleries','gallery_photos','galleries','gallery_categories','faqs','faq_categories','news','articles','resources','partners','people','project_budgets','project_metrics','project_activities','projects','programs','navigation_items','navigations','page_sections','pages','media','user_roles','roles'] as $table) {
            Schema::dropIfExists($table);
        }
    }
};
