@csrf
<div class="grid gap-6 md:grid-cols-2">
<div><label class="mb-2 block text-sm font-semibold">Section Type *</label><select name="section_type" required class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3">@foreach($types as $key=>$type)<option value="{{ $key }}" @selected(old('section_type',$section->section_type ?? '')===$key)>{{ $type['label'] ?? $key }}</option>@endforeach</select></div>
<div><label class="mb-2 block text-sm font-semibold">Status</label><select name="status" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3"><option value="active" @selected(old('status',$section->status ?? 'active')==='active')>Active</option><option value="inactive" @selected(old('status',$section->status ?? '')==='inactive')>Inactive</option></select></div>
<div><label class="mb-2 block text-sm font-semibold">Title (English)</label><input name="title_en" value="{{ old('title_en',$section->title_en ?? '') }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div><label class="mb-2 block text-sm font-semibold">Title (বাংলা)</label><input name="title_bn" value="{{ old('title_bn',$section->title_bn ?? '') }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div><label class="mb-2 block text-sm font-semibold">Subtitle (English)</label><input name="subtitle_en" value="{{ old('subtitle_en',$section->subtitle_en ?? '') }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div><label class="mb-2 block text-sm font-semibold">Subtitle (বাংলা)</label><input name="subtitle_bn" value="{{ old('subtitle_bn',$section->subtitle_bn ?? '') }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold">Content (English)</label><textarea name="content_en" rows="5" class="w-full rounded-lg border border-gray-300 px-4 py-3">{{ old('content_en',$section->content_en ?? '') }}</textarea></div>
<div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold">Content (বাংলা)</label><textarea name="content_bn" rows="5" class="w-full rounded-lg border border-gray-300 px-4 py-3">{{ old('content_bn',$section->content_bn ?? '') }}</textarea></div>
<div><label class="mb-2 block text-sm font-semibold">Media ID</label><input name="media_id" value="{{ old('media_id',$section->media_id ?? '') }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div><label class="mb-2 block text-sm font-semibold">Sort Order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$section->sort_order ?? 0) }}" class="w-full rounded-lg border border-gray-300 px-4 py-3"></div>
<div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold">Data (JSON)</label><textarea name="data" rows="10" placeholder='{"items":[]}' class="w-full rounded-lg border border-gray-300 px-4 py-3 font-mono text-sm">{{ old('data',isset($section)&&$section->data ? json_encode($section->data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea><p class="mt-1 text-xs text-gray-500">Use this for section-specific structured data. Valid JSON only.</p></div>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ route('admin.pages.edit',$page) }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm">Cancel</a><button class="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white">Save Section</button></div>
