@csrf
<div class="grid gap-6 md:grid-cols-2">
    <div><label class="mb-2 block text-sm font-semibold">Title (English) *</label><input name="title_en" value="{{ old('title_en',$page->title_en ?? '') }}" required class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm focus:border-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200"></div>
    <div><label class="mb-2 block text-sm font-semibold">Title (বাংলা)</label><input name="title_bn" value="{{ old('title_bn',$page->title_bn ?? '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm focus:border-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200"></div>
    <div><label class="mb-2 block text-sm font-semibold">Slug</label><input name="slug" value="{{ old('slug',$page->slug ?? '') }}" placeholder="auto-generated if blank" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm focus:border-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200"></div>
    <div><label class="mb-2 block text-sm font-semibold">Page Type</label><input name="page_type" value="{{ old('page_type',$page->page_type ?? 'standard') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm focus:border-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200"></div>
    <div><label class="mb-2 block text-sm font-semibold">Parent Page</label><select name="parent_id" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3"><option value="">Root Page</option>@foreach($parents as $parent)<option value="{{ $parent->id }}" @selected(old('parent_id',$page->parent_id ?? '')==$parent->id)>{{ $parent->title_en }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm font-semibold">Status</label><select name="status" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3">@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(old('status',$page->status ?? 'draft')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm font-semibold">Sort Order</label><input type="number" name="sort_order" value="{{ old('sort_order',$page->sort_order ?? 0) }}" min="0" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Published At</label><input type="datetime-local" name="published_at" value="{{ old('published_at',isset($page)&&$page->published_at ? $page->published_at->format('Y-m-d\TH:i') : '') }}" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3"></div>
    <div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold">Short Description (English)</label><textarea name="short_description_en" rows="3" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3">{{ old('short_description_en',$page->short_description_en ?? '') }}</textarea></div>
    <div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold">Short Description (বাংলা)</label><textarea name="short_description_bn" rows="3" class="w-full rounded-lg border border-gray-300 bg-white px-4 py-3">{{ old('short_description_bn',$page->short_description_bn ?? '') }}</textarea></div>
</div>
<div class="mt-8 border-t pt-6"><h2 class="mb-4 text-lg font-semibold">SEO</h2><div class="grid gap-6 md:grid-cols-2">
    <input name="seo_title_en" value="{{ old('seo_title_en',$page->seo_title_en ?? '') }}" placeholder="SEO title — English" class="rounded-lg border border-gray-300 px-4 py-3">
    <input name="seo_title_bn" value="{{ old('seo_title_bn',$page->seo_title_bn ?? '') }}" placeholder="SEO title — বাংলা" class="rounded-lg border border-gray-300 px-4 py-3">
    <textarea name="seo_description_en" rows="3" placeholder="SEO description — English" class="rounded-lg border border-gray-300 px-4 py-3">{{ old('seo_description_en',$page->seo_description_en ?? '') }}</textarea>
    <textarea name="seo_description_bn" rows="3" placeholder="SEO description — বাংলা" class="rounded-lg border border-gray-300 px-4 py-3">{{ old('seo_description_bn',$page->seo_description_bn ?? '') }}</textarea>
</div></div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ route('admin.pages.index') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium">Cancel</a><button class="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-gray-800">Save Page</button></div>
